version: "3"

services:
web:
  build:
  context: .
  dockerfile: Dockerfile
  ports:
    - 80:80
  volumes:
    - .:/var/www/html
    - ./vhost/site.conf:/etc/apache2/sites-available/000-default.conf
db:
  image: mariadb:10.4
  container_name: your_db_container_name #EDIT
  environment:
  MYSQL_ROOT_PASSWORD: your_root_password #EDIT
  MYSQL_DATABASE: your_database_name #EDIT
  MYSQL_USER: your_mysql_user #EDIT
  MYSQL_PASSWORD: your_mysql_password #EDIT
  ports:
    - "3306:3306"
  volumes:
    - your_db_volume_name:/var/lib/mysql #EDIT
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: your_phpmyadmin_container_name #EDIT
  links:
    - db
  environment:
  PMA_HOST: your_db_container_name #EDIT
  PMA_PORT: 3306
  PMA_ARBITRARY: 1
  ports:
    - 8081:80

volumes:
your_db_volume_name: #EDIT
